export const DAYS = [
  { id: 'apr16', label: 'Apr 16', name: 'Pre-Events' },
  { id: 'apr17', label: 'Apr 17', name: 'Sangeet' },
  { id: 'apr18', label: 'Apr 18', name: 'Haldi' },
  { id: 'apr19', label: 'Apr 19', name: 'Wedding' },
]

export const events = [
  // ── April 16 ──────────────────────────────────────────────────
  { type: 'note', text: 'Chill, hangout, squeeze dance practice in, and enjoy the resort', day: 'apr16' },
  { id: 'apr16-1', time: '12:45 PM', title: "Kisha's landing", day: 'apr16', group: null },
  { id: 'apr16-2', time: '2:45 PM', title: "Arpit's landing", day: 'apr16', group: null },
  { id: 'apr16-3', time: '7:00 PM', title: 'Assemble wedding bags and separate items per event', location: 'TBD', notes: 'Will communicate when/where when time comes', group: 'all', day: 'apr16' },

  // ── April 17 ──────────────────────────────────────────────────
  { id: 'apr17-1', time: '9:00 AM', endTime: '9:50 AM', title: 'Scope out dance practice areas', owner: 'Sonal', group: 'individual', day: 'apr17' },
  { id: 'apr17-2', time: '10:00 AM', endTime: '10:40 AM', title: 'Wedding Rehearsal', owner: 'Sonal, Kisha, Kriya', location: 'Ocean Terrace', group: 'individual', day: 'apr17' },
  { id: 'apr17-3', time: '12:00 PM', title: 'Dance Practice', location: 'TBD', group: 'cousins-friends', day: 'apr17' },
  { id: 'apr17-4', time: '5:30 PM', title: 'Sangeet starts', location: 'Woodstock Terrace', group: null, day: 'apr17' },
  { id: 'apr17-5', time: '6:30 PM', endTime: '7:30 PM', title: 'Sangeet dance program', location: 'Woodstock Terrace', group: null, day: 'apr17' },
  { id: 'apr17-6', time: '10:30 PM', title: 'Sangeet ends', location: 'Woodstock Terrace', group: null, day: 'apr17' },
  { id: 'apr17-7', time: '11:00 PM', endTime: '1:00 AM', title: 'After Party', location: 'Club Heaven', group: 'cousins-friends', day: 'apr17' },

  // ── April 18 ──────────────────────────────────────────────────
  { id: 'apr18-1', time: '7:30 AM', title: 'Audio Setup', owner: 'Sourabh and Shiv', location: 'Azul Terrace', group: 'individual', day: 'apr18' },
  { id: 'apr18-2', time: '7:30 AM', title: "Order yogurt honey and remind Jaymini aunty since she's making the paste now", owner: 'Sonal', group: 'individual', day: 'apr18' },
  { id: 'apr18-3', time: '8:30 AM', title: 'Haldi starts', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-4', time: '8:30 AM', endTime: '9:00 AM', title: 'Ganesh Pooja: Just parents', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-5', time: '9:30 AM', endTime: '10:20 AM', title: 'Mameru & Varadh', location: 'Azul Terrace', notes: 'Mameru people will walk down aisle · Play song · Everyone walks outside for Varadh · Play Garba song when garba starts · Everyone walks back in and finishes procession', group: null, day: 'apr18' },
  { id: 'apr18-6', time: '10:30 AM', endTime: '11:30 AM', title: 'Grah Shanti', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-7', time: '10:30 AM', endTime: '11:00 AM', title: 'Sonal: get yogurt and honey from room service', owner: 'Sonal', group: 'individual', day: 'apr18' },
  { id: 'apr18-8', time: '10:30 AM', endTime: '11:30 AM', title: 'Kriya: make Haldi Paste', owner: 'Kriya', location: 'Azul Terrace', group: 'individual', day: 'apr18' },
  { id: 'apr18-9', time: '10:30 AM', endTime: '11:30 AM', title: 'Bring towels for couple', owner: 'Shyam', location: 'Azul Terrace', group: 'individual', day: 'apr18' },
  { id: 'apr18-10', time: '11:30 AM', endTime: '12:20 PM', title: 'Application with immediate family', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-11', time: '11:30 AM', endTime: '12:20 PM', title: 'Application with rest of the guests', location: 'Azul Terrace', group: 'cousins-friends', day: 'apr18' },
  { id: 'apr18-12', time: '12:20 PM', endTime: '12:30 PM', title: 'Petal shower + Couple jump in the water', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-13', time: '12:30 PM', title: 'Haldi ends', location: 'Azul Terrace', group: null, day: 'apr18' },
  { id: 'apr18-14', time: '12:30 PM', endTime: '2:30 PM', title: 'Haldi lunch', location: 'Azul Terrace', group: null, day: 'apr18' },

  // ── April 19: Baraat & Ceremony ───────────────────────────────
  { type: 'section', title: '✦ Baraat & Ceremony ✦', day: 'apr19' },
  { type: 'note', text: 'Wedding day: No meat. Bride will be fasting — fruits, water, coffee only.', day: 'apr19' },
  { id: 'apr19-1', time: '3:00 AM', title: 'Order fruits, breakfast, water, coffee for hair & makeup room', owner: 'Sonal', group: 'individual', day: 'apr19' },
  { id: 'apr19-2', time: '3:30 AM', endTime: '4:45 AM', title: 'Hair and Makeup', owner: 'Kriya', group: 'individual', day: 'apr19' },
  { id: 'apr19-3', time: '4:45 AM', endTime: '5:30 AM', title: 'Hair and Makeup', owner: 'Sonal', group: 'individual', day: 'apr19' },
  { id: 'apr19-4', time: '5:30 AM', endTime: '6:15 AM', title: 'Hair', owner: 'Ruchi', group: 'individual', day: 'apr19' },
  { id: 'apr19-5', time: '5:30 AM', endTime: '6:15 AM', title: 'Makeup', owner: 'Falguni', group: 'individual', day: 'apr19' },
  { id: 'apr19-6', time: '6:15 AM', endTime: '7:00 AM', title: 'Makeup', owner: 'Ruchi', group: 'individual', day: 'apr19' },
  { id: 'apr19-7', time: '6:15 AM', endTime: '7:00 AM', title: 'Hair', owner: 'Falguni', group: 'individual', day: 'apr19' },
  { id: 'apr19-8', time: '6:15 AM', endTime: '7:00 AM', title: 'Hair', owner: 'Samaica', group: 'individual', day: 'apr19' },
  { id: 'apr19-9', time: '7:00 AM', endTime: '7:45 AM', title: 'Hair and Makeup', owner: 'Shrimi', group: 'individual', day: 'apr19' },
  { id: 'apr19-10', title: "Get Mangalsutra from Arpit's mom", owner: 'Kriya', group: 'individual', day: 'apr19' },
  { id: 'apr19-11', time: '8:00 AM', endTime: '9:00 AM', title: 'Family and bridal party photos', group: 'cousins-friends', day: 'apr19' },
  { id: 'apr19-12', time: '9:00 AM', title: 'Bring flower arrangements to Woodstock Terrace + decorate baarat car on arrival', owner: 'Falguni and Ruchi', location: 'Woodstock Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-13', time: '9:00 AM', title: 'Take umbrellas to Baraat location from bridal photos spot', owner: 'Jay Patel', location: 'TBC', group: 'individual', day: 'apr19' },
  { id: 'apr19-14', time: '9:20 AM', endTime: '10:00 AM', title: 'Baraat', location: 'Woodstock Terrace', group: null, day: 'apr19' },
  { id: 'apr19-15', time: '9:30 AM', title: 'Give Manisha Foi Wedding Bag', owner: 'Kriya', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-16', time: '9:30 AM', title: 'Wedding Breakfast Served', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-17', time: '9:45 AM', endTime: '10:00 AM', title: 'Welcoming of Arpit', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-18', time: '10:10 AM', title: 'Everyone takes seats at ceremony area', notes: 'Announcement: Everyone take their seats and stay seated during entrances', owner: 'Beloved Planners + DJ + Sonal', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-19', time: '10:10 AM', title: 'Entrances Start', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-20', time: '10:10 AM', title: 'Groomsmen line up for entrance', location: 'Ocean Terrace', group: 'groomsmen', day: 'apr19' },
  { id: 'apr19-21', time: '10:20 AM', title: 'Groomsmen enter', notes: 'Manan · Darshit, Adnan · Parva, Kunal · Dhaval, Janam · Maharshi, Dhruvkumar · Dhruv Mehta, Shivang · Jay', location: 'Ocean Terrace', group: 'groomsmen', day: 'apr19' },
  { id: 'apr19-22', time: '10:20 AM', title: "Groom entrance with bride's parents (Jaymini & Hereen Patel) + Groom's parents (Jayshree & Nitin Patel)", owner: 'Kriya', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-23', time: '10:30 AM', title: 'Ceremony starts', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-24', title: 'Ganesh Pooja', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-25', title: "Vaar Pujan (Wash Arpit's feet)", location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-26', title: 'Magalashtaka / Antarpat', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-27', time: '10:40 AM', title: 'Line up all bridal party', location: 'Ocean Terrace', group: 'bridesmaids', day: 'apr19' },
  { id: 'apr19-28', time: '10:45 AM', title: 'Bridal party entrance', notes: 'Order: Sonal · Samaica · Shrimi · Allie · Janu · Krupa · Yeezy · Kriya', location: 'Ocean Terrace', group: 'bridesmaids', day: 'apr19' },
  { id: 'apr19-29', title: 'Ring Bearer entrance', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-30', title: 'Flower Girls entrance', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-31', title: 'Kanya Agaman / Bride entrance', notes: 'Escorts: Shiv Tailor · Karna Thakkar · Shyam Tailor · Sourabh Sharma · Yash Patel · Jay Patel', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-32', title: 'Jai Mala — Exchange of garlands', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-33', title: 'Cheda Chedi', owner: 'Falguni', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-34', title: 'Var Mala — Thread garland around bride and groom', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-35', title: 'Hasta Melap', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-36', title: 'Kanya Daan — Giving away the bride', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-37', title: 'Switch chairs to side by side', owner: 'Jay and Manan', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-38', title: 'Come to Mandap for Mangal Pheras to throw flowers', notes: "Follow Kriya and Sonal's direction on where to line up", location: 'Ocean Terrace', group: 'all', day: 'apr19' },
  { id: 'apr19-39', title: 'Agni Puja & Mangal Phera — The Sacred fire', notes: 'Phera 1: Yash · Phera 2: Jay · Phera 3: Shivam · Phera 4: Shiv, Shyam, Karna, Sourabh', location: 'Ocean Terrace', group: 'individual', day: 'apr19' },
  { id: 'apr19-40', title: 'Saptapadi — The seven steps', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-41', title: 'Mangalsutra — The sacred Auspicious thread', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-42', title: 'Kansar Boojan', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-43', title: 'Sindoor, Mangalsutra, Rings exchange', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-44', title: 'Hand out flower petals for exit', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-45', title: 'Akhand Saubhagyavati — Bridal blessings by elder married women', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-46', title: 'Aashirvaad — Blessing from family', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-47', time: '12:00 PM', title: 'Ceremony ends — Walking down the aisle', location: 'Ocean Terrace', group: null, day: 'apr19' },
  { id: 'apr19-48', time: '12:10 PM', endTime: '1:00 PM', title: 'Group photos', notes: 'You will be notified of your photo group number — please be on the lookout', group: null, day: 'apr19' },
  { id: 'apr19-49', time: '1:00 PM', endTime: '1:30 PM', title: 'Vidaai', group: null, day: 'apr19' },
  { id: 'apr19-50', time: '1:00 PM', endTime: '3:00 PM', title: 'Lunch after ceremony', location: 'Ballroom', group: null, day: 'apr19' },

  // ── April 19: Reception ───────────────────────────────────────
  { type: 'section', title: '✦ Reception ✦', day: 'apr19' },
  { id: 'apr19-51', time: '6:00 PM', endTime: '7:00 PM', title: 'Cocktail hour', location: 'Ballroom Foyer', group: null, day: 'apr19' },
  { id: 'apr19-52', time: '7:00 PM', title: 'Reception starts', location: 'Ballroom', group: null, day: 'apr19' },
  { id: 'apr19-53', time: '7:00 PM', endTime: '7:30 PM', title: 'Line up for entrance + Champagne Toast', location: 'Outside Ballroom door', group: 'all', day: 'apr19' },
  { id: 'apr19-54', time: '7:30 PM', endTime: '7:45 PM', title: 'Entrances: Groom parents · Bride parents · Bridesmaids · Groomsmen · Couple', owner: 'DJ Kru', location: 'Ballroom', group: null, day: 'apr19' },
  { id: 'apr19-55', time: '7:45 PM', endTime: '7:50 PM', title: 'Bride and groom dance performance', notes: 'Only couple will stay on dance floor', location: 'Ballroom', group: null, day: 'apr19' },
  { id: 'apr19-56', time: '7:50 PM', endTime: '9:30 PM', title: 'Reception Program', location: 'Ballroom', group: null, day: 'apr19' },
  { id: 'apr19-57', time: '9:30 PM', endTime: '9:45 PM', title: 'Couple + bridal party + family backdrop photos', location: 'Ballroom', group: 'all', day: 'apr19' },
  { id: 'apr19-58', time: '9:45 PM', title: 'Group Photo + dance floor opens', location: 'Ballroom', group: 'cousins-friends', day: 'apr19' },
  { id: 'apr19-59', time: '12:00 AM', title: 'Reception ends', location: 'Ballroom', group: null, day: 'apr19' },
  { id: 'apr19-60', title: 'After party', location: 'TBD', group: 'cousins-friends', day: 'apr19' },
]
